import type {
  ChordFormula,
  ChordFormulaBehavior,
  ChordFormulaId,
  ChordFormulaTone,
  ChordToneBehavior,
  ChordToneRole,
} from "./types";

const tone = (
  semitones: number,
  diatonicSteps: number,
  role: ChordToneRole,
  required: boolean,
  behavior: ChordToneBehavior,
): ChordFormulaTone => ({
  behavior,
  diatonicSteps,
  required,
  role,
  semitones,
});

const behavior = (value: ChordFormulaBehavior): ChordFormulaBehavior => value;

export const chordFormulas: Readonly<Record<ChordFormulaId, ChordFormula>> = {
  major: {
    id: "major",
    displayName: "Major",
    suffix: "",
    romanCase: "upper",
    romanSuffix: "",
    supportsAppliedDominant: true,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(4, 2, "third", true, "structural"),
      tone(7, 4, "fifth", true, "structural"),
    ],
    behavior: behavior({
      family: "triad",
      additions: [],
      alterations: [],
      omittable: [],
      replaces: [],
    }),
  },
  minor: {
    id: "minor",
    displayName: "Minor",
    suffix: "m",
    romanCase: "lower",
    romanSuffix: "",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(7, 4, "fifth", true, "structural"),
    ],
    behavior: behavior({
      family: "triad",
      additions: [],
      alterations: [],
      omittable: [],
      replaces: [],
    }),
  },
  diminished: {
    id: "diminished",
    displayName: "Diminished",
    suffix: "dim",
    romanCase: "lower",
    romanSuffix: "°",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(6, 4, "fifth", true, "alteration"),
    ],
    behavior: behavior({
      family: "triad",
      additions: [],
      alterations: [{ role: "fifth", fromSemitones: 7, toSemitones: 6 }],
      omittable: [],
      replaces: [],
    }),
  },
  augmented: {
    id: "augmented",
    displayName: "Augmented",
    suffix: "aug",
    romanCase: "upper",
    romanSuffix: "+",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(4, 2, "third", true, "structural"),
      tone(8, 4, "fifth", true, "alteration"),
    ],
    behavior: behavior({
      family: "triad",
      additions: [],
      alterations: [{ role: "fifth", fromSemitones: 7, toSemitones: 8 }],
      omittable: [],
      replaces: [],
    }),
  },
  dominant7: {
    id: "dominant7",
    displayName: "Dominant seventh",
    suffix: "7",
    romanCase: "upper",
    romanSuffix: "7",
    supportsAppliedDominant: true,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(4, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(10, 6, "seventh", true, "extension"),
    ],
    behavior: behavior({
      family: "seventh",
      additions: [],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  major7: {
    id: "major7",
    displayName: "Major seventh",
    suffix: "maj7",
    romanCase: "upper",
    romanSuffix: "maj7",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(4, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(11, 6, "seventh", true, "extension"),
    ],
    behavior: behavior({
      family: "seventh",
      additions: [],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  minor7: {
    id: "minor7",
    displayName: "Minor seventh",
    suffix: "m7",
    romanCase: "lower",
    romanSuffix: "7",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(10, 6, "seventh", true, "extension"),
    ],
    behavior: behavior({
      family: "seventh",
      additions: [],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  "half-diminished7": {
    id: "half-diminished7",
    displayName: "Half-diminished seventh",
    suffix: "m7♭5",
    romanCase: "lower",
    romanSuffix: "ø7",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(6, 4, "fifth", true, "alteration"),
      tone(10, 6, "seventh", true, "extension"),
    ],
    behavior: behavior({
      family: "seventh",
      additions: [],
      alterations: [{ role: "fifth", fromSemitones: 7, toSemitones: 6 }],
      omittable: [],
      replaces: [],
    }),
  },
  diminished7: {
    id: "diminished7",
    displayName: "Diminished seventh",
    suffix: "dim7",
    romanCase: "lower",
    romanSuffix: "°7",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(6, 4, "fifth", true, "alteration"),
      tone(9, 6, "seventh", true, "alteration"),
    ],
    behavior: behavior({
      family: "seventh",
      additions: [],
      alterations: [
        { role: "fifth", fromSemitones: 7, toSemitones: 6 },
        { role: "seventh", fromSemitones: 10, toSemitones: 9 },
      ],
      omittable: [],
      replaces: [],
    }),
  },
  sus2: {
    id: "sus2",
    displayName: "Suspended second",
    suffix: "sus2",
    romanCase: "upper",
    romanSuffix: "sus2",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(2, 1, "second", true, "suspension"),
      tone(7, 4, "fifth", true, "structural"),
    ],
    behavior: behavior({
      family: "suspended",
      additions: [],
      alterations: [],
      omittable: [],
      replaces: ["third"],
    }),
  },
  sus4: {
    id: "sus4",
    displayName: "Suspended fourth",
    suffix: "sus4",
    romanCase: "upper",
    romanSuffix: "sus4",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(5, 3, "fourth", true, "suspension"),
      tone(7, 4, "fifth", true, "structural"),
    ],
    behavior: behavior({
      family: "suspended",
      additions: [],
      alterations: [],
      omittable: [],
      replaces: ["third"],
    }),
  },
  add9: {
    id: "add9",
    displayName: "Added ninth",
    suffix: "add9",
    romanCase: "upper",
    romanSuffix: "(add9)",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(4, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(14, 8, "ninth", true, "addition"),
    ],
    behavior: behavior({
      family: "added-tone",
      additions: ["ninth"],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  "minor-add9": {
    id: "minor-add9",
    displayName: "Minor added ninth",
    suffix: "m(add9)",
    romanCase: "lower",
    romanSuffix: "(add9)",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(14, 8, "ninth", true, "addition"),
    ],
    behavior: behavior({
      family: "added-tone",
      additions: ["ninth"],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  major6: {
    id: "major6",
    displayName: "Major sixth",
    suffix: "6",
    romanCase: "upper",
    romanSuffix: "(add6)",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(4, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(9, 5, "sixth", true, "addition"),
    ],
    behavior: behavior({
      family: "sixth",
      additions: ["sixth"],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  minor6: {
    id: "minor6",
    displayName: "Minor sixth",
    suffix: "m6",
    romanCase: "lower",
    romanSuffix: "(add6)",
    supportsAppliedDominant: false,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(3, 2, "third", true, "structural"),
      tone(7, 4, "fifth", false, "structural"),
      tone(9, 5, "sixth", true, "addition"),
    ],
    behavior: behavior({
      family: "sixth",
      additions: ["sixth"],
      alterations: [],
      omittable: ["fifth"],
      replaces: [],
    }),
  },
  dominant7sus4: {
    id: "dominant7sus4",
    displayName: "Dominant seventh suspended fourth",
    suffix: "7sus4",
    romanCase: "upper",
    romanSuffix: "7sus4",
    supportsAppliedDominant: true,
    tones: [
      tone(0, 0, "root", true, "structural"),
      tone(5, 3, "fourth", true, "suspension"),
      tone(7, 4, "fifth", false, "structural"),
      tone(10, 6, "seventh", true, "extension"),
    ],
    behavior: behavior({
      family: "seventh",
      additions: [],
      alterations: [],
      omittable: ["fifth"],
      replaces: ["third"],
    }),
  },
};

export const chordFormulaIds: readonly ChordFormulaId[] = Object.freeze(
  Object.keys(chordFormulas) as ChordFormulaId[],
);

export const isChordFormulaId = (value: unknown): value is ChordFormulaId =>
  typeof value === "string" && Object.hasOwn(chordFormulas, value);

export const getChordFormula = (formulaId: ChordFormulaId): ChordFormula =>
  chordFormulas[formulaId];
